"""empty message

Revision ID: a28e3fc360d9
Revises: 6d2301514ab0
Create Date: 2024-03-27 18:06:13.532032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28e3fc360d9'
down_revision = '6d2301514ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'competitions', 'users', ['organizer_name'], ['name'])
    op.add_column('participants', sa.Column('scoreboard_place', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'scoreboard_place')
    op.drop_constraint(None, 'competitions', type_='foreignkey')
    # ### end Alembic commands ###
