"""empty message

Revision ID: a400f2d558c3
Revises: a28e3fc360d9
Create Date: 2024-03-27 20:03:10.705121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a400f2d558c3'
down_revision = 'a28e3fc360d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'scoreboard_place')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('scoreboard_place', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
