"""empty message

Revision ID: b260d0a60fb6
Revises: a400f2d558c3
Create Date: 2024-03-27 20:12:57.551913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b260d0a60fb6'
down_revision = 'a400f2d558c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('participants_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions', 'participants_count')
    # ### end Alembic commands ###
